// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example.java.grpc;

public final class GrpcTestServiceProto {
  private GrpcTestServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpringJavaConfigExample_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpringJavaConfigExample_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpringJavaConfigExample_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpringJavaConfigExample_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\027SpringJavaConfigExample\"\034\n" +
      "\014HelloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloRepl" +
      "y\022\017\n\007message\030\001 \001(\t2c\n\007Greeter\022X\n\010SayHell" +
      "o\022%.SpringJavaConfigExample.HelloRequest" +
      "\032#.SpringJavaConfigExample.HelloReply\"\000B" +
      "/\n\025com.example.java.grpcB\024GrpcTestServic" +
      "eProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SpringJavaConfigExample_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SpringJavaConfigExample_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpringJavaConfigExample_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_SpringJavaConfigExample_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SpringJavaConfigExample_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpringJavaConfigExample_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
